#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
فحص بسيط لاحتمال Subdomain Takeover:
- DNS: CNAME + A
- HTTP/HTTPS check
- بصمات أساسية قابلة للتوسعة
"""

import argparse
import csv
import dns.resolver
import dns.exception
import requests
from typing import Optional, Dict, Any

# إعداد DNS resolver
resolver = dns.resolver.Resolver()
resolver.lifetime = 3
resolver.timeout = 3

# بصمات بسيطة لبعض المزوّدين (قابلة للتوسعة بسهولة)
FINGERPRINTS: dict[str, list[str]] = {
    "github_pages": [
        "there isn't a github pages site here",
        "404. page not found · github pages"
    ],
    "heroku": [
        "no such app",
        "there's nothing here, yet.",
        "heroku | no such app"
    ],
    "aws_s3": [
        "the specified bucket does not exist",
        "no such bucket",
        "404 not found</title><body><h1>not found</h1>"
    ],
    "azure": [
        "this web app has been stopped",
        "the resource you are looking for has been removed"
    ],
    "cloudfront": [
        "error from cloudfront",
        "generated by cloudfront"
    ],
    "shopify": [
        "sorry, this shop is currently unavailable",
        "shopify"
    ],
    "unbounce": [
        "the page you were looking for doesn't exist",
        "unbounce"
    ],
}


def dns_get_cname(subdomain: str) -> Optional[str]:
    """إرجاع CNAME لو موجود، أو None لو ما فيه / فشل."""
    try:
        answers = resolver.resolve(subdomain, "CNAME")
        return str(answers[0].target).rstrip(".")
    except (dns.resolver.NoAnswer,
            dns.resolver.NXDOMAIN,
            dns.resolver.NoNameservers,
            dns.exception.Timeout):
        return None


def dns_resolves(name: str) -> bool:
    """محاولة حل اسم (A أو AAAA) وإرجاع True/False."""
    try:
        resolver.resolve(name, "A")
        return True
    except (dns.resolver.NXDOMAIN,
            dns.resolver.NoAnswer,
            dns.resolver.NoNameservers,
            dns.exception.Timeout):
        # جرّب AAAA كاحتمال إضافي
        try:
            resolver.resolve(name, "AAAA")
            return True
        except (dns.resolver.NXDOMAIN,
                dns.resolver.NoAnswer,
                dns.resolver.NoNameservers,
                dns.exception.Timeout):
            return False


def http_check(subdomain: str) -> tuple[Optional[str], Optional[int], str]:
    """
    تجربة HTTP ثم HTTPS (أو العكس) وإرجاع:
    (scheme المستخدم, status code, body النصي أو string فاضية)
    """
    schemes = ["https", "http"]  # HTTPS أولاً غالباً أدق
    headers = {
        "User-Agent": "SubTake-Checker/1.0 (+https://example.com)"
    }

    for scheme in schemes:
        url = f"{scheme}://{subdomain}"
        try:
            r = requests.get(url, headers=headers, timeout=7, allow_redirects=True)
            body = r.text[:15000].lower()  # نكتفي بأول 15000 حرف للتحليل
            return scheme, r.status_code, body
        except requests.RequestException:
            continue

    return None, None, ""


def match_fingerprint(body: str) -> Optional[str]:
    """محاولة مطابقة محتوى الصفحة مع بصمات معروفة."""
    if not body:
        return None

    for provider, patterns in FINGERPRINTS.items():
        for pat in patterns:
            if pat.lower() in body:
                return provider
    return None


def check_subdomain(subdomain: str) -> Dict[str, Any]:
    """فحص ساب دومين واحد وإرجاع نتيجة مفصلة في dict."""
    result: Dict[str, Any] = {
        "subdomain": subdomain,
        "cname": None,
        "cname_resolves": None,
        "a_record": None,
        "http_scheme": None,
        "http_status": None,
        "fingerprint": None,
        "possible_takeover": False,
        "notes": "",
    }

    # تنظيف سريع للاسم
    sd = subdomain.strip().lstrip(".")
    if not sd or ".." in sd or " " in sd:
        result["notes"] = "اسم دومين غير صالح بعد التنظيف"
        return result

    # 1) فحص CNAME
    cname = dns_get_cname(sd)
    result["cname"] = cname

    if cname:
        # 1.1) هل الهدف في CNAME يحلّ؟
        cname_ok = dns_resolves(cname)
        result["cname_resolves"] = cname_ok

        if not cname_ok:
            # مؤشر قوي لاحتمال Takeover
            result["possible_takeover"] = True
            result["notes"] = "CNAME يشير إلى هدف لا يمكن حله (قد يكون غير مسجل)"
            # مع هذا، نستمر في الفحص HTTP للمزيد من الدلائل
    else:
        result["notes"] = "لا يوجد CNAME"

    # 2) فحص A record (الساب دومين نفسه)
    a_ok = dns_resolves(sd)
    result["a_record"] = a_ok

    # 3) فحص HTTP/HTTPS
    scheme, status, body = http_check(sd)
    result["http_scheme"] = scheme
    result["http_status"] = status

    if status is None and not result["notes"]:
        result["notes"] = "تعذر الوصول عبر HTTP/HTTPS"

    # 4) مطابقة بصمات المحتوى مع مزوّدين
    fp = match_fingerprint(body)
    result["fingerprint"] = fp

    # 5) منطق تحديد possible_takeover النهائي
    # - CNAME لا يحلّ  -> strong signal
    # - أو fingerprint مريبة لمزوّد معروف مع HTTP شغال
    if fp:
        result["possible_takeover"] = True
        if result["notes"]:
            result["notes"] += f" | fingerprint محتملة: {fp}"
        else:
            result["notes"] = f"fingerprint محتملة: {fp}"

    return result


def main(input_file: str, output_file: Optional[str] = None):
    # قراءة الساب دومينات من الملف وتنظيفها
    with open(input_file, "r", encoding="utf-8") as f:
        raw_subs = [line.strip() for line in f if line.strip()]

    subs: list[str] = []
    seen: set[str] = set()
    for s in raw_subs:
        s = s.strip().lstrip(".")
        if not s or ".." in s or " " in s:
            print(f"[!] تخطي اسم غير صالح: {s!r}")
            continue
        if s in seen:
            continue
        seen.add(s)
        subs.append(s)

    results: list[Dict[str, Any]] = []

    for sub in subs:
        print(f"[+] فحص: {sub}")
        try:
            res = check_subdomain(sub)
        except Exception as e:
            # لا نخلي أي استثناء يطيح السكربت بالكامل
            res = {
                "subdomain": sub,
                "cname": None,
                "cname_resolves": None,
                "a_record": None,
                "http_scheme": None,
                "http_status": None,
                "fingerprint": None,
                "possible_takeover": False,
                "notes": f"خطأ غير متوقع: {e}",
            }

        results.append(res)

        status_txt = "محتمل استيلاء" if res["possible_takeover"] else "لا يوجد مؤشر قوي"
        print(f"    CNAME: {res['cname']}")
        print(f"    CNAME يحلّ؟ {res['cname_resolves']}")
        print(f"    A record يحلّ؟ {res['a_record']}")
        print(f"    HTTP: {res['http_scheme']} status={res['http_status']}")
        print(f"    Fingerprint: {res['fingerprint']}")
        print(f"    الحالة: {status_txt}")
        if res["notes"]:
            print(f"    ملاحظات: {res['notes']}")
        print("-" * 60)

    # حفظ النتائج في CSV (اختياري)
    if output_file:
        fieldnames = [
            "subdomain",
            "cname",
            "cname_resolves",
            "a_record",
            "http_scheme",
            "http_status",
            "fingerprint",
            "possible_takeover",
            "notes",
        ]
        with open(output_file, "w", newline="", encoding="utf-8") as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            for r in results:
                writer.writerow(r)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Subdomain Takeover checker (CNAME + A + HTTP/HTTPS + fingerprints)"
    )
    parser.add_argument(
        "-i", "--input", required=True,
        help="ملف يحتوي قائمة الساب دومينات (واحد في كل سطر)"
    )
    parser.add_argument(
        "-o", "--output",
        help="ملف CSV لحفظ النتائج (اختياري)"
    )

    args = parser.parse_args()
    main(args.input, args.output)