#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Subdomain Takeover Scanner v2.0
فحص شامل لاحتمال استيلاء على النطاقات الفرعية
"""

import argparse
import csv
import re
import dns.resolver
import dns.exception
import requests
from typing import Optional, Dict, Any, List
from concurrent.futures import ThreadPoolExecutor, as_completed
import socket
import time

# إعداد DNS resolver
resolver = dns.resolver.Resolver()
resolver.lifetime = 5
resolver.timeout = 5

# بصمات موسعة لاحتمال الاستيلاء
FINGERPRINTS = {
    "github_pages": [
        "there isn't a github pages site here",
        "404. page not found · github pages",
        "this site is owned by github",
        "github pages",
        "project doesn't exist",
    ],
    "heroku": [
        "no such app",
        "there's nothing here, yet",
        "heroku | no such app",
        "herokuapp.com",
    ],
    "aws_s3": [
        "the specified bucket does not exist",
        "no such bucket",
        "404 not found</title>",
        "amazonaws.com/s3",
        "accessdenied",
    ],
    "azure": [
        "this web app has been stopped",
        "the resource you are looking for has been removed",
        "azurewebsites.net",
        "does not exist",
        "azure",
        "azurefd.net",
    ],
    "cloudfront": [
        "error from cloudfront",
        "generated by cloudfront",
        "cloudfront",
    ],
    "shopify": [
        "sorry, this shop is currently unavailable",
        "shopify",
        "myshopify.com",
    ],
    "firebase": [
        "firebase hosting",
        "does not exist",
        "firebaseapp.com",
    ],
    "fastly": [
        "fastly error",
        "fastly",
    ],
    "netlify": [
        "not found",
        "netlify.app",
    ],
}

# قائمة نطاقات مزودين يمكن الاستيلاء عليها
VULNERABLE_PROVIDERS = [
    "github.io",
    "herokuapp.com",
    "azurewebsites.net",
    "cloudapp.net",
    "s3.amazonaws.com",
    "amazonaws.com",
    "firebaseapp.com",
    "azurefd.net",
    "netlify.app",
    "fastly.net",
]

def clean_domain(input_str):
    """تنظيف السلسلة لاستخراج النطاق فقط"""
    if not input_str:
        return None
    
    input_str = input_str.strip().lower()
    
    # إزالة البروتوكول
    if input_str.startswith(('http://', 'https://')):
        input_str = input_str.split('://', 1)[1]
    
    # إزالة المسارات
    input_str = input_str.split('/')[0]
    
    # إزالة المنفذ
    if ':' in input_str:
        input_str = input_str.split(':')[0]
    
    # تحقق من صحة النطاق
    pattern = r'^([a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}$'
    
    if re.match(pattern, input_str):
        return input_str
    
    return None

def dns_get_cname(subdomain):
    """إرجاع CNAME لو موجود"""
    try:
        answers = resolver.resolve(subdomain, "CNAME")
        if answers:
            return str(answers[0].target).rstrip(".").lower()
    except:
        pass
    return None

def dns_resolves(name, record_type="A"):
    """محاولة حل اسم DNS"""
    try:
        resolver.resolve(name, record_type)
        return True
    except:
        return False

def http_check(subdomain, timeout=10):
    """فحص HTTP/HTTPS"""
    schemes = ["https", "http"]
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
    }
    
    for scheme in schemes:
        url = f"{scheme}://{subdomain}"
        try:
            r = requests.get(url, headers=headers, timeout=timeout, allow_redirects=True, verify=False)
            return scheme, r.status_code, r.text.lower()
        except:
            continue
    
    return None, None, ""

def match_fingerprint(body):
    """مطابقة بصمات المحتوى"""
    if not body:
        return None
    
    for provider, patterns in FINGERPRINTS.items():
        for pat in patterns:
            if pat.lower() in body:
                return provider
    
    return None

def is_vulnerable_provider(cname):
    """فحص إذا كان CNAME يشير إلى مزود قابل للاستيلاء"""
    if not cname:
        return False
    
    cname_lower = cname.lower()
    for provider in VULNERABLE_PROVIDERS:
        if provider in cname_lower:
            return True
    
    return False

def check_subdomain(subdomain, timeout=10):
    """فحص ساب دومين واحد"""
    result = {
        "subdomain": subdomain,
        "cname": None,
        "cname_resolves": None,
        "a_record": None,
        "http_scheme": None,
        "http_status": None,
        "fingerprint": None,
        "vulnerable_provider": False,
        "possible_takeover": False,
        "confidence": "low",
        "notes": "",
    }
    
    # فحص CNAME
    cname = dns_get_cname(subdomain)
    result["cname"] = cname
    
    if cname:
        cname_ok = dns_resolves(cname, "A")
        result["cname_resolves"] = cname_ok
        
        vulnerable = is_vulnerable_provider(cname)
        result["vulnerable_provider"] = vulnerable
        
        if not cname_ok and vulnerable:
            result["possible_takeover"] = True
            result["confidence"] = "high"
            result["notes"] = f"CNAME يشير إلى {cname} ولا يمكن حله"
        elif not cname_ok:
            result["possible_takeover"] = True
            result["confidence"] = "medium"
            result["notes"] = f"CNAME يشير إلى {cname} ولا يمكن حله"
        elif vulnerable:
            result["possible_takeover"] = True
            result["confidence"] = "medium"
            result["notes"] = f"CNAME يشير إلى مزود قابل للاستيلاء: {cname}"
    else:
        result["notes"] = "لا يوجد CNAME"
    
    # فحص A record
    result["a_record"] = dns_resolves(subdomain, "A")
    
    # فحص HTTP
    scheme, status, body = http_check(subdomain, timeout)
    result["http_scheme"] = scheme
    result["http_status"] = status
    
    # مطابقة البصمات
    fp = match_fingerprint(body)
    result["fingerprint"] = fp
    
    if fp:
        result["possible_takeover"] = True
        if result["confidence"] == "low":
            result["confidence"] = "medium"
        if result["notes"]:
            result["notes"] += f" | fingerprint: {fp}"
        else:
            result["notes"] = f"fingerprint: {fp}"
    
    return result

def extract_subdomains_from_file(filename):
    """قراءة الملف واستخراج الساب دومينات"""
    subdomains = []
    seen = set()
    
    try:
        with open(filename, 'r', encoding='utf-8', errors='ignore') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                
                domain = clean_domain(line)
                if domain and domain not in seen:
                    seen.add(domain)
                    subdomains.append(domain)
    except Exception as e:
        print(f"[!] خطأ في قراءة الملف: {e}")
        return []
    
    return subdomains

def print_results_summary(results):
    """طباعة ملخص النتائج"""
    total = len(results)
    possible = sum(1 for r in results if r["possible_takeover"])
    with_cname = sum(1 for r in results if r["cname"])
    
    print("\n" + "="*60)
    print("ملخص النتائج:")
    print("="*60)
    print(f"إجمالي النطاقات: {total}")
    print(f"بها CNAME: {with_cname}")
    print(f"محتملة للاستيلاء: {possible}")
    
    if possible > 0:
        print("\nالحالات المحتملة:")
        for r in results:
            if r["possible_takeover"]:
                icon = "🔥" if r["confidence"] == "high" else "⚠️"
                print(f"  {icon} {r['subdomain']}")
                print(f"    CNAME: {r['cname']}")
                print(f"    الثقة: {r['confidence']}")
                print(f"    السبب: {r['notes']}")
                if r['fingerprint']:
                    print(f"    Fingerprint: {r['fingerprint']}")
                print()
    
    print("="*60)

def main():
    parser = argparse.ArgumentParser(description="Subdomain Takeover Scanner")
    parser.add_argument("-i", "--input", required=True, help="ملف الساب دومينات")
    parser.add_argument("-o", "--output", help="ملف CSV لحفظ النتائج")
    parser.add_argument("-t", "--threads", type=int, default=10, help="عدد الثريدات")
    parser.add_argument("--timeout", type=int, default=10, help="مهلة الطلبات")
    
    args = parser.parse_args()
    
    print("="*60)
    print("Subdomain Takeover Scanner v2.0")
    print("="*60)
    
    # قراءة الساب دومينات
    subdomains = extract_subdomains_from_file(args.input)
    if not subdomains:
        print("[!] لا توجد نطاقات صالحة")
        return
    
    print(f"[+] تم تحميل {len(subdomains)} نطاق")
    print("[+] بدء الفحص...")
    print("-"*60)
    
    results = []
    
    # فحص كل نطاق
    for i, sub in enumerate(subdomains, 1):
        print(f"[{i}/{len(subdomains)}] فحص: {sub}")
        try:
            res = check_subdomain(sub, args.timeout)
            results.append(res)
            
            icon = "🔥" if res["confidence"] == "high" else "⚠️" if res["possible_takeover"] else "✓"
            status = "محتمل" if res["possible_takeover"] else "آمن"
            print(f"    {icon} {status} (ثقة: {res['confidence']})")
            if res['cname']:
                print(f"    CNAME: {res['cname']}")
            if res['fingerprint']:
                print(f"    Fingerprint: {res['fingerprint']}")
        except Exception as e:
            print(f"    [!] خطأ: {e}")
        
        print("-"*40)
    
    # عرض النتائج
    print_results_summary(results)
    
    # حفظ النتائج
    if args.output:
        try:
            fieldnames = ["subdomain", "cname", "cname_resolves", "a_record", 
                         "http_scheme", "http_status", "fingerprint", 
                         "vulnerable_provider", "possible_takeover", 
                         "confidence", "notes"]
            
            with open(args.output, 'w', newline='', encoding='utf-8') as csvfile:
                writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
                writer.writeheader()
                for r in results:
                    writer.writerow(r)
            
            print(f"[+] تم حفظ النتائج في: {args.output}")
        except Exception as e:
            print(f"[!] خطأ في حفظ النتائج: {e}")
    
    print("\n[+] انتهى الفحص")

if __name__ == "__main__":
    main()
